# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            inklecate_windows_and_linux.zip
            inkle/
          key: ${{ runner.os }}-${{ hashFiles('./inklecate_windows_and_linux.zip') }}
            
      - name: get inkle.
        id: get
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/inkle/ink/releases/download/0.9.0/inklecate_windows_and_linux.zip -O ./inklecate_windows_and_linux.zip
          7z x inklecate_windows_and_linux.zip -oinkle

      - name: build
        run: |
          mono inkle/inklecate.exe -o temp.json Entry.ink
          cp -rf template dist
          echo "var storyContent = " > temp.txt
          cat temp.txt temp.json > dist/story.js
      - name: Invoke Deployment
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
        uses: JamesIves/github-pages-deploy-action@3.2.1
      - name: clean
        run:
          ls | grep -v img | xargs rm -rf
          mv img/* .
          rm -rf img/
      - name: uptoc
        uses: saltbo/uptoc@v1.4.3
        with:
          driver: cos
          region: ap-shanghai
          bucket: self-1251738611
        env: 
          UPTOC_UPLOADER_AK: ${{ secrets.SID }}
          UPTOC_UPLOADER_SK: ${{ secrets.SKEY }}
