# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            inklecate_windows_and_linux.zip
            inkle/
          key: ${{ runner.os }}-${{ hashFiles('./inklecate_windows_and_linux.zip') }}
            
      - name: get inkle.
        id: get
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/inkle/ink/releases/download/0.9.0/inklecate_windows_and_linux.zip -O ./inklecate_windows_and_linux.zip
          7z x inklecate_windows_and_linux.zip -oinkle

      - name: build
        run: |
          mono inkle/inklecate.exe -o temp.json Entry.ink
          cp -rf template dist
          echo "var storyContent = " > temp.txt
          cat temp.txt temp.json > dist/story.js
      - name: Invoke Deployment
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
        uses: JamesIves/github-pages-deploy-action@3.2.1
      - name: uptoc
        run: |
          wget https://github.com/saltbo/uptoc/releases/download/v1.4.3/uptoc-linux-amd64.tar.gz
          tar xf uptoc-linux-amd64.tar.gz
          cd img/
          ../uptoc --driver cos --region ap-shanghai --bucket self-1251738611 --access_key ${{ secrets.SID }} --secret_key ${{ secrets.SKEY }} .
